"""
Django settings for ProjetIoT project.
Generated by 'django-admin startproject' using Django 4.2.7.
"""

import os
from pathlib import Path


# =====================
# BASE
# =====================
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = "django-insecure-&d)%-+-i(-nqrm-1q*-1mhn@jwn#(4^bk_bikr5plz=de%&(@&"
DEBUG = True
ALLOWED_HOSTS = ["*"]


# =====================
# APPLICATIONS
# =====================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",
    "DHT",
]


# =====================
# MIDDLEWARE
# =====================
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",

    # CSRF ON (ok) - on utilise token côté JS
    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "ProjetIoT.urls"


# =====================
# TEMPLATES  ✅ (CORRIGÉ)
# =====================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        # templates global (BASE_DIR/templates)
        "DIRS": [BASE_DIR / "templates"],

        # templates dans app/templates/
        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    }
]


WSGI_APPLICATION = "ProjetIoT.wsgi.application"


# =====================
# DATABASE
# =====================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# =====================
# VOIP / ASTERISK (POC)
# Désactivé par défaut => ne casse rien tant que tu n'as pas installé Asterisk
# =====================
VOIP_ENABLED = False  # <-- mets True quand Asterisk est prêt

ASTERISK_AMI_HOST = "127.0.0.1"
ASTERISK_AMI_PORT = 5038
ASTERISK_AMI_USER = "django_admin"
ASTERISK_AMI_PASSWORD = "supersecret"

# extension SIP à appeler (ton MicroSIP / Zoiper)
SIP_TARGET_EXTENSION = "6001"

# Seuil critique: counter >= 7 => appel (selon ta règle)
VOIP_CRITICAL_COUNTER = 7



# =====================
# PASSWORD VALIDATION
# =====================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# =====================
# I18N / TIMEZONE
# =====================
LANGUAGE_CODE = "fr-fr"
TIME_ZONE = "Africa/Casablanca"
USE_I18N = True
USE_TZ = True


# =====================
# STATIC FILES
# =====================
STATIC_URL = "static/"

# dossier "static" au niveau du projet (BASE_DIR/static)
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# utile si un jour tu fais collectstatic
STATIC_ROOT = BASE_DIR / "staticfiles"


# =====================
# DEFAULT PK
# =====================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =====================
# DJANGO REST FRAMEWORK
# =====================
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
}


# =====================
# EMAIL (GMAIL SMTP)
# =====================
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "noureddinesaadaoui20010401@gmail.com"

# ⚠️ idéalement à mettre dans .env (mais je te le laisse comme tu l’as)
EMAIL_HOST_PASSWORD = "qrhu wzaa alnp kwsr"

TELEGRAM_BOT_TOKEN = "8213192070:AAFdzwHOWo9Jg0DcMFf9sLer1uC0Y2kcr14"
TELEGRAM_CHAT_ID = "6942932296"


# =====================
# MQTT CONFIGURATION
# =====================
MQTT_HOST = "192.168.137.17"
MQTT_PORT = 1883
MQTT_TOPIC_SENSOR = "sensors/+/dht11"


# =====================
# THRESHOLDS
# Plage normale: [10 ; 23]
# Alerte froide: T < 10
# Alerte chaude: T > 23
# =====================
TEMP_MIN_THRESHOLD = 10.0
TEMP_MAX_THRESHOLD = 23.0
ALERT_COOLDOWN_SECONDS = 60


# =====================
# AUTH (TP PROF) - Login/Logout
# =====================
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/login/"
