# Generated by Django 5.2.7 on 2025-12-27 17:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('counter', models.IntegerField(default=0)),
                ('max_temp', models.FloatField(default=0)),
                ('op1_ack', models.BooleanField(default=False)),
                ('op2_ack', models.BooleanField(default=False)),
                ('op3_ack', models.BooleanField(default=False)),
                ('op1_comment', models.TextField(blank=True)),
                ('op2_comment', models.TextField(blank=True)),
                ('op3_comment', models.TextField(blank=True)),
                ('op1_saved_at', models.DateTimeField(blank=True, null=True)),
                ('op2_saved_at', models.DateTimeField(blank=True, null=True)),
                ('op3_saved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dht11',
            options={'ordering': ['-dt']},
        ),
        migrations.RemoveField(
            model_name='dht11',
            name='date',
        ),
        migrations.AddField(
            model_name='dht11',
            name='dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dht11',
            name='hum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dht11',
            name='temp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
