# Generated by Django 4.2.16 on 2026-01-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DHT", "0002_incident_alter_dht11_options_remove_dht11_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="last_alert_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="is_open",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="max_temp",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
