# Generated by Django 5.2.6 on 2026-01-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0003_incident_last_alert_at_alter_incident_is_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('HOT', 'Température haute'), ('COLD', 'Température basse')], default='HOT', max_length=10),
        ),
        migrations.AddField(
            model_name='incident',
            name='min_temp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
