# Generated by Django 5.2.6 on 2026-01-03 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0004_incident_incident_type_incident_min_temp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-start_at']},
        ),
        migrations.RemoveField(
            model_name='incident',
            name='min_temp',
        ),
        migrations.AddField(
            model_name='incident',
            name='max_allowed_temp',
            field=models.FloatField(default=23.0),
        ),
        migrations.AddField(
            model_name='incident',
            name='min_allowed_temp',
            field=models.FloatField(default=10.0),
        ),
        migrations.CreateModel(
            name='OperatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('prenom', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operator Profile',
                'verbose_name_plural': 'Operator Profiles',
            },
        ),
    ]
