# Generated by Django 5.2.6 on 2026-01-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0005_alter_incident_options_remove_incident_min_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='min_temp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
