# Generated by Django 5.2.6 on 2026-01-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0006_incident_min_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='voip_triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
